<a href="https://colab.research.google.com/github/hiten4/Day25AM/blob/main/Day25_AM_PartA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 25 AM — Part A

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
 'category': np.random.choice(['A','B','C'],500),
 'value': np.random.randint(10,100,500),
 'value2': np.random.randint(5,50,500)
})

df.head()

  category  value  value2
0        C     57       8
1        B     77      19
2        C     55      31
3        C     34      13
4        A     36      33

In [2]:
df.head()
df.tail()

    category  value  value2
495        B     38      38
496        A     90      15
497        B     16      19
498        A     18      40
499        A     45      27

In [3]:
df.shape
df.columns

Index(['category', 'value', 'value2'], dtype='object')

In [4]:
df.isnull().sum()

category    0
value       0
value2      0
dtype: int64

In [5]:
df.describe()

            value      value2
count  500.000000  500.000000
mean    52.144000   27.836000
std     26.455378   13.195809
min     10.000000    5.000000
25%     29.000000   17.000000
50%     51.000000   27.500000
75%     74.000000   40.000000
max     99.000000   49.000000

In [6]:
df['category'].unique()
df['category'].value_counts()

category
B    181
A    163
C    156
Name: count, dtype: int64