<a href="https://colab.research.google.com/github/hiten4/Day25AM/blob/main/Day25_AM_PartB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 25 AM — Part B

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
 'category': np.random.choice(['A','B','C'],500),
 'value': np.random.randint(10,100,500),
 'value2': np.random.randint(5,50,500)
})

In [2]:
df[(df['value'] > 50) & (df['category']=='A')]

    category  value  value2
7          A     71      46
11         A     91      30
15         A     69      15
16         A     69       9
34         A     65      24
..       ...    ...     ...
488        A     75      15
490        A     99      37
493        A     53      22
497        A     76      22
499        A     53      31

[101 rows x 3 columns]

In [3]:
df['new_col'] = df['value'] * 2

In [4]:
df.sort_values(by='value', ascending=False).head()

    category  value  value2  new_col
289        A     99      14      198
64         C     99      19      198
325        C     99      29      198
321        A     99      15      198
384        C     99      36      198

In [5]:
df.groupby('category')['value'].mean()

category
A    55.615819
B    52.126506
C    50.324841
Name: value, dtype: float64